### ISSUE TITLE
Setting style via function in ol.Feature

### ISSUE THREAD

**Issue by gkresic** [TDesjardins/gwt-ol3#90]
According to OpenLayers, `ol.Feature` should support passing function to `setStyle` method:

https://openlayers.org/en/latest/apidoc/ol.Feature.html#setStyle

gwt-ol3, however, does not support it.

I'm not very fluent in JsInterop, but I suspect that has something to do with special treatment of keyword `this` inside that function. On the other hand, `ol.Feature::setStyle` supports the same `ol.StyleFunction` as `ol.layer.Vector::setStyle` that already works fine in current gwt-ol3.
Is there a straightforward way to support this feature? If so, I could try to make a patch, possibly with some guidance on JsInterop specifics.

**Comment by TDesjardins** [comment]
I think there is a simple solution for this. I will soon make a commit. Would be nice if you could test this.

**Comment by TDesjardins** [comment]
Done! https://github.com/TDesjardins/gwt-ol3/commit/ad766af7f129ccf24c2ff99c0eeef5939e3968ae
Could you test this?

**Comment by gkresic** [comment]
Partially :)

Functions gets called, but parameters are not right. Looks like OL is passing **two** parameters to style function (feature and resolution), but my style function gets only **second** one - resolution, which is only a number, not an feature object (that I need).

Two parameters are indeed in documentation:

https://openlayers.org/en/latest/apidoc/ol.html#.StyleFunction

I verified invocation (ol-debug.js, v4.2.0, around line 61894):

```
var styles;
var styleFunction = feature.getStyleFunction();
if (styleFunction) {
  styles = styleFunction.call(feature, resolution);  // <-- HERE
} else {
  styleFunction = vectorLayer.getStyleFunction();
  if (styleFunction) {
    styles = styleFunction(feature, resolution);
  }
}
```

**Comment by gkresic** [comment]
I forgot my Java code:

```
ol.Feature feature = new ol.format.Wkt().readFeature(backing.getWkt(), wktReadOptions);
feature.setId(backing.getId().toString());
feature.setStyle(object -> getStyle(object));
```

and style function:

```
private ol.style.Style[] getStyle(ol.Feature feature) {
   feature.get();   // results in TypeError: feature_0_g$.getId is not a function (indeed it isn't, 'feature' is a number as seen in DevTools)
}
```

**Comment by gkresic** [comment]
I've tried defining specialized `StyleFunction` for usage it in `Feature::setStyle`:

```
@JsFunction
public interface StyleFunction<R> {
	R call(Feature feature, double resolution);
}
```

but unfortunately, it still does not work: first parameter is still a number (resolution) and second one is undefined.

**Comment by TDesjardins** [comment]
Yes, I can reproduce this. Actually that should work but it doesn't. That's weird. The StyleFunction has two params but the implementation should also work with one parameter.
Seems that the problem is a result of jsinterop internals in combination with ol implementation. The function `createStyleFunction` checks the number of parameters of the StyleFunction (see https://github.com/openlayers/openlayers/blob/master/src/ol/feature.js#L294). The StyleFunction should usually have two parameters. JsInterop wraps the implementation of your functional interface function, which has two params, in another function which has no params. Therfore the correct function will not be called. If I remove the check it works like expected.
Nevertheless it should work if check fails because the method was directly assigned (see https://github.com/openlayers/openlayers/blob/master/src/ol/feature.js#L299). But only the resolution parameter is considered. Strange!

But apart from that I think you don't need any parameter at all because the StyleFunction is a closure and because of that you can access the feature and the resolution from surrounded context.

**Comment by TDesjardins** [comment]
Maybe we should only include the resolution param. So we could bypass the type errors. The users could access the feature by closure.

**Comment by TDesjardins** [comment]
I changed the style function to work with resolution only for now to bypass the class cast issue. I am leaving this issue open because maybe this is a JsInterop bug.

**Comment by TDesjardins** [comment]
@gkresic The style function has now two params and should work as expected.
